### ISSUE TITLE
Add ESlint standard style

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#1]
add ESlint Standard Style

[https://github.com/standard/eslint-config-standard](https://github.com/standard/eslint-config-standard)

it will change package.json and add .eslintrc

**Comment by wildan3105** [comment]
Hi, I can work on this. Do you give me a chance? @bossbossk20

**Comment by felipesousa** [comment]
hey @bossbossk20, i can take this issue?

**Comment by bossbossk20** [comment]
@felipesousa Yeah

**Comment by felipesousa** [comment]
@bossbossk20  nice! :) :octocat:

**Comment by felipesousa** [comment]
@bossbossk20 done!

**Comment by bossbossk20** [comment]
Good job @felipesousa
