### ISSUE TITLE
Update README.md with usage instructions

### ISSUE THREAD

**Issue by ashwani99** [bossbossk20/youtube-player-socket.io#14]
Currently there is no usage instructions fro new users to run it locally.

**Comment by bossbossk20** [comment]
@ashwani99 Can you do it.

**Comment by bossbossk20** [comment]
example 

how to install 
```shell
$ npm install
```

show to run 
```shell
$ npm start 
```
build 
```shell
$ npm run build
```

**Comment by reo-ar** [comment]
sorry, missed that thing, please do it, or contact me to do it.

**Comment by bossbossk20** [comment]
@cairnifex Don't worry.  You can do it if you want.

**Comment by exler** [comment]
Done. #19

**Comment by sameerkumar18** [comment]
Working on this :)

**Comment by bossbossk20** [comment]
@exler Good job.
