### ISSUE TITLE
add github ribbon

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#16]
add GitHub Ribbon on the left corner 

[example](https://github.com/blog/273-github-ribbons)

**Comment by TheCodeArtist** [comment]
I would like to do this.

Can you confirm that the right way to do this would be to 
add the code-snippet from the given [example](https://github.com/blog/273-github-ribbons) into `App.js` at Line 71?...

https://github.com/bossbossk20/youtube-player-socket.io/blob/f9e4b65e49bf32d566cd15c0dfb8062f00cde355/src/App.js#L70-L75

**Comment by bossbossk20** [comment]
@TheCodeArtist Sure, let do it.

**Comment by devesh-verma** [comment]
@bossbossk20 I would like to work on this.

**Comment by bossbossk20** [comment]
@devshiva619 let's pull request.

**Comment by TheCodeArtist** [comment]
@bossbossk20 Please review #18 

Searching online, apparently an alternate approach could be as follows:

```
(function(){
	var mlink=document.createElement('a');
	mlink.setAttribute("href","https://github.com/bossbossk20/youtube-player-socket.io/");
	mlink.setAttribute("style","    position: absolute; top: 0; right: 0; z-index: 1000;");
	mlink.innerHTML='<img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png">';
	document.body.insertBefore(mlink, document.body.childNodes[0]);
})();
```

But being new to javascript, am not sure how to call the above `function()`

Is PR #18 acceptable or any suggestions on how to use the above code-snippet?

**Comment by bossbossk20** [comment]
still open

**Comment by TheCodeArtist** [comment]
Finally figured out how to update a PR. 🤣  
(basically `commit --amend` and a `push -f` handles it )

@bossbossk20 i've pushed updates to PR #18 please review.

**Comment by gowthamrm** [comment]
@bossbossk20 Can we make use of this [Component](https://github.com/jessy1092/react-github-fork-ribbon) instead? This is a pure CSS implementation of fork me ribbon. We can avoid loading an image for the ribbon if we use this component.

**Comment by bossbossk20** [comment]
@gowthamrm  yeah let do it 👍

**Comment by gowthamrm** [comment]
@bossbossk20 Done in #25 👍
