### ISSUE TITLE
add github ribbon

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#2]
add GitHub ribbon to the left corner

 [Ribbon example](https://github.com/blog/273-github-ribbons)

**Comment by ashwani99** [comment]
@bossbossk20 Hey can I take this?

**Comment by bossbossk20** [comment]
@ashwani99  Sure let do it

**Comment by bossbossk20** [comment]
Add github ribbon in react

**Comment by bossbossk20** [comment]
Still Open

**Comment by ashwani99** [comment]
@bossbossk20 I am working on it
