### ISSUE TITLE
Have any idea

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#27]
Do you have any idea? @gowthamrm

**Comment by gowthamrm** [comment]
@bossbossk20 Regarding? 🤔 

If you mean about improving the project, then yeah we need to update the UI first, it can be more colorful. 😄

**Comment by gowthamrm** [comment]
@bossbossk20 If you mean about improving the project, then yeah we need to update the UI first. 😄

**Comment by bossbossk20** [comment]
@gowthamrm if you have any idea you can do it. 

I think I will add 
- chat 
- react-router
- mobx or redux

what do you think ?

**Comment by gowthamrm** [comment]
@bossbossk20 Can you elaborate on the idea you have on the project, say first we can list the feature set. Later we can find a technical way to fix it.

Actually, I work in ember just started exploring react. But as far as my knowledge I don't see we will require react-router for this app. As it doesn't have much routing necessity in it. If you have new features to add on it which will require routing in the app, we can then explore and add it.

**Comment by bossbossk20** [comment]
in the future, I think it will have more pages and more complex.

**Comment by gowthamrm** [comment]
Then fine, we can proceed with it 👍

**Comment by soumam007** [comment]
1. Can you add a next / prev button to swap the videos.
2. You can add a download button that would directly link you to savefrom.net from where you can download the video as per quality
3. You can add a voice search by using annyang.js  which will convert speech to text.

**Comment by bossbossk20** [comment]
@soumam007 Cool I need next / prev button.

**Comment by gowthamrm** [comment]
@bossbossk20 Also, Clicking on the Particular Video from the Playlist should play that Video. It would be better if we have this option too.

**Comment by bossbossk20** [comment]
@gowthamrm Can you open an issue. 👍

**Comment by gowthamrm** [comment]
@bossbossk20 Added a new issue. #41 👍
