### ISSUE TITLE
change inline css in react to styled-component 

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#28]
I want to change inline-css in react to styled-component

[https://github.com/styled-components/styled-components](https://github.com/styled-components/styled-components)

<a href="https://www.styled-components.com">
  <img alt="styled-components" src="https://raw.githubusercontent.com/styled-components/brand/master/styled-components.png" height="150px" />
</a>

**Comment by QuadDepo** [comment]
Will try this for hacktober :-)

**Comment by bossbossk20** [comment]
@QuadDepo Sure 👍

**Comment by ericadamski** [comment]
@QuadDepo if you need anything I can back you up on this!

**Comment by bossbossk20** [comment]
@QuadDepo  Sure you can do it.
