### ISSUE TITLE
Website title should be changed to application name

### ISSUE THREAD

**Issue by ashwani99** [bossbossk20/youtube-player-socket.io#29]
Currently, the title of https://youtube-socket.firebaseapp.com/ is React App. It should be changed to application name i.e YouTube Socket (I am not sure about this). What do you think @bossbossk20

**Comment by bossbossk20** [comment]
@ashwani99 Can you do it.

I recommend you use this 

[https://github.com/nfl/react-helmet](https://github.com/nfl/react-helmet)

**Comment by ashwani99** [comment]
@bossbossk20 I need to learn to use react-helmet. If anyone else want to do it, do it else I will do it.

**Comment by thompsonemerson** [comment]
@bossbossk20 did you see? I implemented the [react-helmet](https://github.com/nfl/react-helmet) no PR #30
