### ISSUE TITLE
Separate react component 

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#3]
Right now, youtube player and playlist stay together. I want to separate it from App.js

example  App.js
```html
<div>
  <Player />
  <Playlist />
</div>

```

**Comment by AzrizHaziq** [comment]
@bossbossk20 , I'm currently splitting your component

**Comment by bossbossk20** [comment]
@TwinLight  push your code and Pull Request

**Comment by gowthamrm** [comment]
@bossbossk20 I couldn't find the newly added components `Player` and `PlayerList` in the master branch. Something went wrong?

**Comment by bossbossk20** [comment]
@gowthamrm It cannot add music to a player. so I have to make it work first 

Can you check it again.

**Comment by gowthamrm** [comment]
@bossbossk20 Sure, Let me give a try...

**Comment by gowthamrm** [comment]
@bossbossk20 Done the same in #26. Can you check if this will do?
