### ISSUE TITLE
Add youtube icon to favicon 

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#32]
Add youtube icon to favicon

**Comment by fabiomirandaa** [comment]
I will take this one

**Comment by bossbossk20** [comment]
@fabiomirandaa Go ahead 👍

**Comment by rattandeep1998** [comment]
Added favicon.

**Comment by trdwll** [comment]
Same here lol. #36

**Comment by bossbossk20** [comment]
I will review tomorrow, too sleepy.

actually, it should put favicon at Helmet in src/App.js

@fabiomirandaa @rattandeep1998  @trdwll
