### ISSUE TITLE
Project LICENSE not present

### ISSUE THREAD

**Issue by ashwani99** [bossbossk20/youtube-player-socket.io#4]
A project license should be added to the repository

**Comment by bossbossk20** [comment]
can you do it @ashwani99

**Comment by ashwani99** [comment]
@bossbossk20 Sure, but what kind of license do you want to be added? https://choosealicense.com/ Also, can you add a label for hacktoberfest for this?

**Comment by bossbossk20** [comment]
@ashwani99  MIT please :sparkles:
