### ISSUE TITLE
Option to select a particular video to play from the playlist

### ISSUE THREAD

**Issue by gowthamrm** [bossbossk20/youtube-player-socket.io#41]
Clicking on the particular video should play from the playlist should play that video.

We must handle below things,

- [ ] 1. Option to select a video to be played.

- [ ] 2. Active video should be shown prominently in the playlist.

- [ ] 3. We need **not remove** the video from the playlist once the video is completed. 
(Currently, we show only the first video in the list, once the video is ended we remove that video from the list, so that the next video is pushed to the top of the list and its starts playing. I guess we can remove this behaviour now. @bossbossk20 Your thoughts on this?)

**Comment by khw1031** [comment]
I think I can try these things. Is it okay to try?

**Comment by bossbossk20** [comment]
@khw1031 Of course. 👍
