### ISSUE TITLE
Add any unit test 

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#45]
Add any unit test

**Comment by cjdeleon62** [comment]
Hi, @bossbossk20 I can write a unit test for Player.js. I'll try to get it done by tonight

**Comment by cjdeleon62** [comment]
@bossbossk20, would it be okay to add extra packages useful for unit testing like sinon and enzyme?

**Comment by bossbossk20** [comment]
@cjdeleon62 Sure I want more test as much as possible
