### ISSUE TITLE
Have the playlist display more intuitively

### ISSUE THREAD

**Issue by mdew192837** [bossbossk20/youtube-player-socket.io#48]
I don't think the playlist should be displayed when you add something to the playlist. That's what the successful message is for.

I think playlist should be on the left side permanently, and a button to toggle to hide or show it.

**Comment by bossbossk20** [comment]
@mdew192837 Yeah I think so. 👍

**Comment by mdew192837** [comment]
Cool, I'm messaging you on gitter, can you chat there? @bossbossk20
