### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#67]
Wrap everything to container

**Comment by karannaoh** [comment]
Can I work on It?

**Comment by bossbossk20** [comment]
Sure

**Comment by karannaoh** [comment]
`From node`
`Run git clone https://github.com/bossbossk20/youtube-player-socket.io`
`workdir youtube-player-socket.io`
`Run npm install && npm build`
`CMD npm start`

this is what I am doing if you can please have a look

**Comment by t04glovern** [comment]
I wrote something for another project and I've tested it works on this. I can submit the PR if that's all ok? just don't want to step on toes
