### ISSUE TITLE
Add eslint standard for react and babel  

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#8]
ESlint still not working on React right now. 

example
[https://github.com/standard/eslint-config-standard-react](https://github.com/standard/eslint-config-standard-react) 

and add babel to eslint

[https://github.com/babel/babel-eslint](https://github.com/babel/babel-eslint)

**Comment by phillip055** [comment]
Assign Me!

**Comment by bossbossk20** [comment]
@phillip055  let do it. :smiley:

**Comment by bossbossk20** [comment]
@phillip055  someone done it
