### ISSUE TITLE
Add cool description in readme.md

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/youtube-player-socket.io#9]
Add a cool description on readme.md 

I need cool description

**Comment by reo-ar** [comment]
I can do this, can you give me a brief overview of the use of this program though?

**Comment by bossbossk20** [comment]
@cairnifex  just youtube player  and you can try it

https://music.kody-koy.me

**Comment by reo-ar** [comment]
sure assign it to me, working on it

**Comment by bossbossk20** [comment]
yeah, let do it. @cairnifex

**Comment by bossbossk20** [comment]
Cool thank you @cairnifex
